//
var SAMCMD = {};

SAMCMD.CMDLOGIN                    = 1;
SAMCMD.CMDNOTIFYDISCONNECT         = 37;
SAMCMD.CMDPINGPONG                 = 50;
SAMCMD.CMDJOINROOM                = 3001;
SAMCMD.CMDRECONNECTGAMEROOM      = 3002;
SAMCMD.CMDJOINROOMFAIL           = 3004;
SAMCMD.QUICKROOMSUCCEED          = 3006;

SAMCMD.CMDQUYETDINHSAM             = 3100;
SAMCMD.CMDDANHBAI                  = 3101;
SAMCMD.CMDSTARTGAME                = 3102;
SAMCMD.CMDENDGAME                  = 3103;

SAMCMD.CMDCHIABAI                  = 3105;
SAMCMD.CMDBOLUOT                   = 3106;
SAMCMD.CMDAUTOSTART                = 3107;
SAMCMD.CMDFIRSTTURN                = 3108;
SAMCMD.CMDBAOSAM                   = 3109;
SAMCMD.CMDUPDATEGAMEINFO           = 3110;
SAMCMD.CMDREQUESTLEAVEROOM         = 3111;
SAMCMD.CMDCHANGETURN               = 3112;
SAMCMD.CMDCHATCHONG                = 3113;
SAMCMD.CMDHUYBAOSAM                = 3114;
SAMCMD.CMDCHEATBAI                 = 3115;
SAMCMD.CMDHOLD                     = 3116;
SAMCMD.CMDJOINROOMSUCCESS        = 3118;

SAMCMD.CMDUSERLEAVEROOM        = 3119;
SAMCMD.CMDNOTIFYKICKOFF          = 3120;
SAMCMD.CMDUSERJOINROOM           = 3121;
SAMCMD.CMDUPDATEMATH               = 3123;
SAMCMD.READYAUTOSTART             = 3124;
SAMCMD.MONEYBETCONFIG             = 3003;
SAMCMD.GETLISTROOM             = 3014;
SAMCMD.TOPSERVER                  = 1001;
SAMCMD.CHEATCARD                  = 3115;