//
var BAICAOCMD = {};

BAICAOCMD.CMDLOGIN                    = 1;
BAICAOCMD.CMDPINGPONG               = 1050;
BAICAOCMD.CMDJOINROOM                = 3001;
BAICAOCMD.CMDRECONNECTGAMEROOM      = 3002;
BAICAOCMD.CMDJOINROOMFAIL           = 3004;
BAICAOCMD.QUICKROOMSUCCEED          = 3006;

BAICAOCMD.CMDMOBAI                      = 3101;
BAICAOCMD.CMDYEUCAUDANHBIEN             = 3104;
BAICAOCMD.CMDCHAPNHANDANHBIEN           = 3108;
BAICAOCMD.CMDDATCUOC                   = 3109;
BAICAOCMD.CMDKECUA                     = 3106;
BAICAOCMD.CMDBATDAU                     = 3102;
BAICAOCMD.CMDENDGAME                    = 3103;
BAICAOCMD.CMDCHIABAI                    = 3105;
BAICAOCMD.CMDTUDONGBATDAU               = 3107;
BAICAOCMD.CMDTHONGTINBANCHOI            = 3110;
BAICAOCMD.CMDVAOGA                      = 3112;
BAICAOCMD.CMDDOICHUONG                  = 3113;
BAICAOCMD.CMDMOIDATCUOC               = 3114;

BAICAOCMD.CMDREQUESTLEAVEROOM         = 3111;
BAICAOCMD.CMDCHEATBAI                 = 3115;
BAICAOCMD.CMDHOLD                     = 3116;
BAICAOCMD.CMDJOINROOMSUCCESS             = 3118;
BAICAOCMD.CMDUSERLEAVEROOM                  = 3119;
BAICAOCMD.CMDNOTIFYKICKOFF              = 3120;
BAICAOCMD.CMDUSERJOINROOM                 = 3121;
BAICAOCMD.CMDNOTIFYGETJACKPOT            = 3122;
BAICAOCMD.CMDUPDATEMATCH                 = 3123;

