//
var TIENLENCMD = {};

TIENLENCMD.CMDLOGIN                    = 1;
TIENLENCMD.CMDNOTIFYDISCONNECT         = 37;
TIENLENCMD.CMDPINGPONG                 = 50;
TIENLENCMD.CMDJOINROOM                = 3001;
TIENLENCMD.QUICKROOMSUCCEED          = 3006;

TIENLENCMD.CMDDANHBAI                  = 3101;
TIENLENCMD.CMDSTARTGAME                = 3102;
TIENLENCMD.CMDENDGAME                  = 3103;

TIENLENCMD.CMDCHIABAI                  = 3105;
TIENLENCMD.CMDBOLUOT                   = 3106;
TIENLENCMD.CMDAUTOSTART                = 3107;
TIENLENCMD.CMDFIRSTTURN                = 3108;
TIENLENCMD.CMDUPDATEGAMEINFO           = 3110;
TIENLENCMD.CMDREQUESTLEAVEROOM         = 3111;
TIENLENCMD.CMDCHANGETURN               = 3112;
TIENLENCMD.CMDCHATCHONG                = 3113;
TIENLENCMD.CMDHOLD                     = 3116;
TIENLENCMD.CMDJOINROOMSUCCESS        = 3118;

TIENLENCMD.CMDUSERLEAVEROOM        = 3119;
TIENLENCMD.CMDNOTIFYKICKOFF          = 3120;
TIENLENCMD.CMDUSERJOINROOM           = 3121;
TIENLENCMD.CMDUPDATEMATH               = 3123;
TIENLENCMD.CMDWAIT4DOITHONG            = 3124;