//
var BACAYCMD = {};

BACAYCMD.CMDLOGIN                    = 1;
BACAYCMD.CMDPINGPONG               = 1050;
BACAYCMD.CMDJOINROOM                = 3001;
BACAYCMD.CMDRECONNECTGAMEROOM      = 3002;
BACAYCMD.CMDJOINROOMFAIL           = 3004;
BACAYCMD.QUICKROOMSUCCEED          = 3006;

BACAYCMD.CMDMOBAI                      = 3101;
BACAYCMD.CMDYEUCAUDANHBIEN             = 3104;
BACAYCMD.CMDCHAPNHANDANHBIEN           = 3108;
BACAYCMD.CMDDATCUOC                   = 3109;
BACAYCMD.CMDKECUA                     = 3106;
BACAYCMD.CMDBATDAU                     = 3102;
BACAYCMD.CMDENDGAME                    = 3103;
BACAYCMD.CMDCHIABAI                    = 3105;
BACAYCMD.CMDTUDONGBATDAU               = 3107;
BACAYCMD.CMDTHONGTINBANCHOI            = 3110;
BACAYCMD.CMDVAOGA                      = 3112;
BACAYCMD.CMDDOICHUONG                  = 3113;
BACAYCMD.CMDMOIDATCUOC               = 3114;

BACAYCMD.CMDREQUESTLEAVEROOM         = 3111;
BACAYCMD.CMDCHEATBAI                 = 3115;
BACAYCMD.CMDHOLD                     = 3116;
BACAYCMD.CMDJOINROOMSUCCESS             = 3118;
BACAYCMD.CMDUSERLEAVEROOM                  = 3119;
BACAYCMD.CMDNOTIFYKICKOFF              = 3120;
BACAYCMD.CMDUSERJOINROOM                 = 3121;
BACAYCMD.CMDNOTIFYGETJACKPOT            = 3122;
BACAYCMD.CMDUPDATEMATCH                 = 3123;

BACAYCMD.MONEYBETCONFIG             = 3003;
BACAYCMD.TOPSERVER                  = 1001;

